name: Android emulator
on:
  workflow_dispatch:
    
env:
  # On Ubuntu, we install the Android SDK in the workspace directory.
  ANDROID_HOME: ${{ github.workspace }}/android-sdk
  ANDROID_ARCH: arm64-v8a
  ANDROID_TARGET: google_apis_playstore
  API_LEVEL: 33
  ANDROID_BUILD_TOOLS_VERSION: 33.0.2
  # Use an ARM64 system image (adjust if needed for your host architecture)
  ANDROID_SDK_PACKAGES: system-images;android-33;google_apis_playstore;arm64-v8a platforms;android-33 build-tools;33.0.2 platform-tools emulator
  EMULATOR_TIMEOUT: 350
  EMULATOR_NAME: nexus

jobs:
  playwright-emulator:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Add avdmanager and sdkmanager to system PATH
        run: |
          echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/${ANDROID_BUILD_TOOLS_VERSION}" >> $GITHUB_PATH

      - name: Install SDK
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install ${ANDROID_SDK_PACKAGES}
  
      - name: Create AVD
        run: |
          # Create the AVD using the ARM64 ABI
          echo "no" | avdmanager --verbose create avd --force -n $EMULATOR_NAME --abi "arm64-v8a" -k "system-images;android-${API_LEVEL};${ANDROID_TARGET};${ANDROID_ARCH}"
          
      - name: Launch emulator
        run: |
          # Launch the emulator headlessly (without window, audio, boot animation, or snapshots)
          $ANDROID_HOME/emulator/emulator -avd $EMULATOR_NAME -no-window -no-audio -no-boot-anim -no-snapshot -gpu swiftshader_indirect &
      
      - name: Wait for emulator to boot
        run: |
          adb wait-for-device
          bootcompleted=$(adb shell getprop sys.boot_completed | tr -d '\r')
          while [ "$bootcompleted" != "1" ]; do
            echo "Waiting for emulator to boot... (sys.boot_completed = $bootcompleted)"
            sleep 5
            bootcompleted=$(adb shell getprop sys.boot_completed | tr -d '\r')
          done
          echo "Emulator booted successfully!"
