name: Android emulator
on:
  workflow_dispatch:
    
env:
  ANDROID_HOME: /Users/runner/Library/Android/sdk
  ANDROID_ARCH: x86_64
  ANDROID_TARGET: google_apis_playstore
  API_LEVEL: 33
  ANDROID_BUILD_TOOLS_VERSION: 33.0.2
  ANDROID_SDK_PACKAGES: system-images;android-33;google_apis_playstore;x86_64 platforms;android-33 build-tools;33.0.2 platform-tools emulator
  EMULATOR_TIMEOUT: 350
  EMULATOR_NAME: nexus

jobs:
  playwright-emulator:
    timeout-minutes: 20
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add Android tools to PATH
        run: |
          echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/${ANDROID_BUILD_TOOLS_VERSION}" >> $GITHUB_PATH

      - name: Accept licenses and install SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install ${ANDROID_SDK_PACKAGES}

      - name: Create AVD
        run: |
          # Use "x86_64" for the ABI since the system image is for x86_64.
          echo "no" | avdmanager --verbose create avd --force -n $EMULATOR_NAME --abi "x86_64" -k "system-images;android-${API_LEVEL};${ANDROID_TARGET};${ANDROID_ARCH}"

      - name: Launch emulator
        run: |
          # Launch the emulator headlessly (without window, audio, boot animation, or snapshots)
          $ANDROID_HOME/emulator/emulator -avd $EMULATOR_NAME -no-window -no-audio -no-boot-anim -no-snapshot -gpu swiftshader_indirect &

      - name: Wait for emulator to boot
        run: |
          # Wait until the emulator reports boot completed
          adb wait-for-device
          bootcompleted=$(adb shell getprop sys.boot_completed | tr -d '\r')
          while [ "$bootcompleted" != "1" ]; do
            echo "Waiting for emulator to boot... (sys.boot_completed = $bootcompleted)"
            sleep 5
            bootcompleted=$(adb shell getprop sys.boot_completed | tr -d '\r')
          done
          echo "Emulator booted successfully!"
